### ISSUE TITLE
Satellite view in this plugin 

### ISSUE THREAD

**Issue by sandy01101987** [miya0001/simple-map#10]
Hello,

I am happy to use this plugin but one problem is that how can we see Satellite view in this Google map which is appearing with help of this plugin. Is there any shortcode or extra command?

Please help as son as possible!

**Comment by SiamKreative** [comment]
If @miya0001 wants to add a shortcode attribute, this could be helpful:
* https://hpneo.github.io/gmaps/examples/map_types.html
* https://github.com/hpneo/gmaps/issues/106

**Comment by miya0001** [comment]
:+1: 

Please wait a couple of days!

**Comment by miya0001** [comment]
Released.

https://ja.wordpress.org/plugins/simple-map/
