### ISSUE TITLE
Vertical copyright statement of google cutting across the map image

### ISSUE THREAD

**Issue by daphne-yu83** [miya0001/simple-map#13]
![untitled](https://cloud.githubusercontent.com/assets/12500220/7686032/785b2594-fdc5-11e4-9000-030ebf9737e8.png)

The Google Map copyright statement is cutting across the image file of the map at my website: http://revemarketing.com.sg/contact-us-2/.
Any solutions?

**Comment by SiamKreative** [comment]
Looks like they solved, you should close this @miya0001 :)

**Comment by miya0001** [comment]
:smile:
