### ISSUE TITLE
REFUND

### ISSUE THREAD

**Issue by SoBold** [miya0001/simple-map#15]
We want a refund ASAP.

We have reached out to you and heard nothing back from you.

Please email will@soboldltd.com ASAP

**Comment by miya0001** [comment]
Uh? It's a free and open source, so I didn't get money from you.
I think you are misunderstanding with another plugin.

**Comment by miya0001** [comment]
Could you tell me URL of the plugin.

**Comment by kimipooh** [comment]
Hi SoBold. 
Aren't  you using Maps Made Simple for WordPress plugin(http://simplemap-plugin.com/)?
