### ISSUE TITLE
モバイルの表示について。

### ISSUE THREAD

**Issue by no23h** [miya0001/simple-map#19]
素晴らしいプラグインありがとうございます。
一点質問なのですが、モバイルの場合のみ地図が表示されません。

コンソールで確認したところ以下のようなエラーがでました。
GET http://maps.googleapis.com/maps/api/staticmap?center=34.679367,135.4967577&size=480x200&sensor=true&zoom=16&markers=34.679367,135.4967577&scale=2 403 (Forbidden)

google static mapsの画像が取得できていないようなのですが、
解決策はありますでしょうか。

**Comment by miya0001** [comment]
ちょっと試していただきたいのですが、Google MapのAPIキーをURLに追加したら表示されますか？

**Comment by miya0001** [comment]
あっ、追加というのはブラウザのアドレス欄でという意味です。

**Comment by marushu** [comment]
@no23h さん、Google Static Maps APIは有効化されていますでしょうか。
https://console.developers.google.com/project
こちらで各プロジェクトのダッシュボードで取得したAPIを確認できます。

また、APIキーを使用するURLの設定で、
*.example.com/*
上記のような設定になっていますでしょうか。

**Comment by kznr28** [comment]
今までGoogle Static Maps APIを使用していなかったドメインで使用する場合に、APIキーが必須となったみたいです。生成されるimg要素のsrc属性にAPIキーを追加した場合に画像が表示されました。

**Comment by no23h** [comment]
@miya0001 さま、ご回答ありがとうございます。
また返信が遅くなりまして申し訳ありません。
APIキーをURLに追加というのは、どのように記述すればよいのでしょうか。

**Comment by no23h** [comment]
@marushu さま
お返事が遅くなりまして申し訳ありません。
Google Static Maps APIは有効になっておりました。
またURLの設定も問題ありませんでした。

**Comment by nakaguma** [comment]
お世話になります。
私も今までGoogle Static Maps APIを使用しておらず、初めて使った者ですが、全く同じ状況です。
@kznr28さんのように、生成されるimg要素のsrc属性に

&key=○○○○○○○○

APIキーを追加してみましたら、以下のようなエラーメッセージが出ました。

The Google Maps API server rejected your request. Invalid request. Missing the 'size' parameter.

APIキーを追加したsrcのソースを確認しますと、確かに

%E2%80%A6e=480x200

と文字化けを起こしていましたので、

&size=480x200

と修正しましたら、きちんと地図が画像で表示されました。

①APIを追加する
②サイズパラメーターの文字化けを修正

私の場合は、上記２点を加えることで表示できました。

**Comment by miya0001** [comment]
@nakaguma そのAPIキーというのは普通のGoogle MAPのAPIキーと同じでも動作しますか？
ドキュメントを見る手間を省きたいのでぜひご教示いただけると幸いです。

**Comment by nakaguma** [comment]
@miya0001様、普通のといって良いのかわからないですが、PCで表示されたものと同じAPIキーです。質問の意味を間違っていたら、すみません…！

**Comment by miya0001** [comment]
I fixed a problem of the API key on the static map.
Please try v2.14.3 and tell me if you have any problem.
Thanks!

スタティックマップでのAPIキーの不具合を修正しました。
v2.14.3（最新版）をお試しいただいて、もし問題があれば再度ご教示いただきたくお願いいたします。

**Comment by nakaguma** [comment]
@miya0001様、早速プラグインアップデートさせていただきましたら、スマホではStatic Mapsがバッチリ表示されていました。
ありがとうございました！

**Comment by miya0001** [comment]
こちらこそ確認ありがとうございます。あと対応がおそくなってすいません。

**Comment by no23h** [comment]
@miya0001様、私もアップデートしましたら無事表示されました！
ご対応いただきまして誠にありがとうございます！
