### ISSUE TITLE
Deferred loading of Google Maps API script?

### ISSUE THREAD

**Issue by glueckpress** [miya0001/simple-map#23]
Thanks for this great plugin, I love the simplicity! 🙏 

I wondered what you may think about loading scripts deferred?
Tested with this little helper plugin, works like a charm for me.
https://gist.github.com/glueckpress/56c88900aad391b95b5d44f4e752a1a4

Would there be any objections making this a default?

**Comment by miya0001** [comment]
I am sorry for late reply.

It looks nice. Do you know are there any problems if we make this as a default.
Thanks!

**Comment by glueckpress** [comment]
As long as no other (inline) JavaScript that depends on the deferred scripts gets loaded before the two deferred ones, I don’t see any issues. 

Hadn’t had a chance to test extensively, though, it was just a quick tweak for me. Ideally this would be tested by a couple of more people to get a bit of data in.

**Comment by glueckpress** [comment]
Yeah. Sorry for leaving this open so long. 😄 Can’t seem to make time for testing, so closing.
